version: '3.7'

services:
  mongodb_container:
    image: mongo
    container_name: mongodb_reactive
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mkt-reactive
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
    - mkt-reactive:/var/lib/mongodb

volumes:
  mkt-reactive:
